// <auto-generated />
using System;
using HistoryPositionService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HistoryPositionService.Migrations
{
    [DbContext(typeof(HistoryPositionContext))]
    partial class HistoryPositionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HistoryPositionService.Models.HistoryPosition", b =>
                {
                    b.Property<int>("HistoryPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Fuel")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("GpsSerialNumber")
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Speed")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("HistoryPositionId");

                    b.ToTable("HistoryPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
